### ISSUE TITLE
Compatibility with xperia 10 ii / sfos 4

### ISSUE THREAD

**Issue by patrickjane** [ichthyosaurus/sailfish-public-patch-sources#2]
Can your patches currently be installed on sfos4 / the xperia 10 ii? E.g. I am trying to get `sfos-patch-keyboard-color-stock-emojis` to work, however when installing via storeman it says that the patchmanager dependency is missing, which is not (yet) working.

Is there any other way to install, or should I just wait for the patchmanager to become available?

**Comment by ichthyosaurus** [comment]
Technically, you can install any patch by applying it manually:

    devel-su patch -R -p1 -d / -i /usr/share/patchmanager/patches/sfos-patch-keyboard-color-stock-emojis/unified_diff.patch

**But** this will "physically" apply the patch. In other words, it actually changes the files and you must remember to remove it properly again for updates. (Patchmanager does not change the actual files - which is why it doesn't work in sailjail, AFAIK.)

Is Patchmanager not yet available for aarch64? Most patches don't change files inside the jail, so I think Patchmanager should work for them. This includes all keyboard patches.

**Comment by patrickjane** [comment]
Okay I see, then I shall wait until patchmanager is available.

**Comment by ichthyosaurus** [comment]
Patchmanager should be compatible with SFOS 4 now. Feel free to reopen this issue if there's any problem. (All patches are still only tested on SFOS 3.4, though.)
