### ISSUE TITLE
Emoji keyboard patch incompatible with Sauna 4.6.0

### ISSUE THREAD

**Issue by direc85** [ichthyosaurus/sailfish-public-patch-sources#6]
I just noticed that the emoji keyboard patch isn't compatible with Sauna 4.6.0.11 - applying the patch fails.

**Comment by ichthyosaurus** [comment]
Thanks for the heads up! That's a shame... Someone created #7 but I didn't have time to test it yet. I also haven't updated to 4.6 yet because I can't risk potentially bricking my phone at the moment. Ideally, I should find a way to make the patch compatible with 4.6 and older versions. Until then, I'm unsure how to proceed.

To be honest, I'm hesitant to put much effort into anything Sailfish-related until it is clear how Jolla continues in the future. If they really go ahead with the "subscription" scheme, I might see myself forced to quit Sailfish altogether. It's just unaffordable for me, and it's also simply beyond shameless to try and extract more money from people who donate thousands of hours of free labour without which Sailfish would be unusable (talking about apps, translations, patches, etc.).

**Comment by ichthyosaurus** [comment]
Version 1.5.2 of the patch should be compatible with 4.5 and 4.6.
